// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: httpMsg.proto

package com.example.nettytest._07Protobuf.pojo;

public final class Company {
  private Company() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>int32 phone = 3;</code>
     * @return The phone.
     */
    int getPhone();

    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    java.util.List<com.example.nettytest._07Protobuf.pojo.Company.Work> 
        getWorksList();
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    com.example.nettytest._07Protobuf.pojo.Company.Work getWorks(int index);
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    int getWorksCount();
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    java.util.List<? extends com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder> 
        getWorksOrBuilderList();
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder getWorksOrBuilder(
        int index);
  }
  /**
   * <pre>
   *生成类 相当于内部类 Company.Employee
   * </pre>
   *
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
      works_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 24: {

              phone_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                works_ = new java.util.ArrayList<com.example.nettytest._07Protobuf.pojo.Company.Work>();
                mutable_bitField0_ |= 0x00000001;
              }
              works_.add(
                  input.readMessage(com.example.nettytest._07Protobuf.pojo.Company.Work.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          works_ = java.util.Collections.unmodifiableList(works_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.nettytest._07Protobuf.pojo.Company.Employee.class, com.example.nettytest._07Protobuf.pojo.Company.Employee.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int PHONE_FIELD_NUMBER = 3;
    private int phone_;
    /**
     * <code>int32 phone = 3;</code>
     * @return The phone.
     */
    @java.lang.Override
    public int getPhone() {
      return phone_;
    }

    public static final int WORKS_FIELD_NUMBER = 4;
    private java.util.List<com.example.nettytest._07Protobuf.pojo.Company.Work> works_;
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.nettytest._07Protobuf.pojo.Company.Work> getWorksList() {
      return works_;
    }
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder> 
        getWorksOrBuilderList() {
      return works_;
    }
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    @java.lang.Override
    public int getWorksCount() {
      return works_.size();
    }
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    @java.lang.Override
    public com.example.nettytest._07Protobuf.pojo.Company.Work getWorks(int index) {
      return works_.get(index);
    }
    /**
     * <pre>
     * 相当于List&lt;Work&gt;
     * </pre>
     *
     * <code>repeated .Work works = 4;</code>
     */
    @java.lang.Override
    public com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder getWorksOrBuilder(
        int index) {
      return works_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (phone_ != 0) {
        output.writeInt32(3, phone_);
      }
      for (int i = 0; i < works_.size(); i++) {
        output.writeMessage(4, works_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (phone_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, phone_);
      }
      for (int i = 0; i < works_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, works_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.nettytest._07Protobuf.pojo.Company.Employee)) {
        return super.equals(obj);
      }
      com.example.nettytest._07Protobuf.pojo.Company.Employee other = (com.example.nettytest._07Protobuf.pojo.Company.Employee) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getPhone()
          != other.getPhone()) return false;
      if (!getWorksList()
          .equals(other.getWorksList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone();
      if (getWorksCount() > 0) {
        hash = (37 * hash) + WORKS_FIELD_NUMBER;
        hash = (53 * hash) + getWorksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.nettytest._07Protobuf.pojo.Company.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *生成类 相当于内部类 Company.Employee
     * </pre>
     *
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        com.example.nettytest._07Protobuf.pojo.Company.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.nettytest._07Protobuf.pojo.Company.Employee.class, com.example.nettytest._07Protobuf.pojo.Company.Employee.Builder.class);
      }

      // Construct using com.example.nettytest._07Protobuf.pojo.Company.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWorksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        phone_ = 0;

        if (worksBuilder_ == null) {
          works_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          worksBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      public com.example.nettytest._07Protobuf.pojo.Company.Employee getDefaultInstanceForType() {
        return com.example.nettytest._07Protobuf.pojo.Company.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.nettytest._07Protobuf.pojo.Company.Employee build() {
        com.example.nettytest._07Protobuf.pojo.Company.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.nettytest._07Protobuf.pojo.Company.Employee buildPartial() {
        com.example.nettytest._07Protobuf.pojo.Company.Employee result = new com.example.nettytest._07Protobuf.pojo.Company.Employee(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.age_ = age_;
        result.phone_ = phone_;
        if (worksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            works_ = java.util.Collections.unmodifiableList(works_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.works_ = works_;
        } else {
          result.works_ = worksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.nettytest._07Protobuf.pojo.Company.Employee) {
          return mergeFrom((com.example.nettytest._07Protobuf.pojo.Company.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.nettytest._07Protobuf.pojo.Company.Employee other) {
        if (other == com.example.nettytest._07Protobuf.pojo.Company.Employee.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getPhone() != 0) {
          setPhone(other.getPhone());
        }
        if (worksBuilder_ == null) {
          if (!other.works_.isEmpty()) {
            if (works_.isEmpty()) {
              works_ = other.works_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWorksIsMutable();
              works_.addAll(other.works_);
            }
            onChanged();
          }
        } else {
          if (!other.works_.isEmpty()) {
            if (worksBuilder_.isEmpty()) {
              worksBuilder_.dispose();
              worksBuilder_ = null;
              works_ = other.works_;
              bitField0_ = (bitField0_ & ~0x00000001);
              worksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWorksFieldBuilder() : null;
            } else {
              worksBuilder_.addAllMessages(other.works_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.nettytest._07Protobuf.pojo.Company.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.nettytest._07Protobuf.pojo.Company.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int phone_ ;
      /**
       * <code>int32 phone = 3;</code>
       * @return The phone.
       */
      @java.lang.Override
      public int getPhone() {
        return phone_;
      }
      /**
       * <code>int32 phone = 3;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(int value) {
        
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 phone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        
        phone_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.example.nettytest._07Protobuf.pojo.Company.Work> works_ =
        java.util.Collections.emptyList();
      private void ensureWorksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          works_ = new java.util.ArrayList<com.example.nettytest._07Protobuf.pojo.Company.Work>(works_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.nettytest._07Protobuf.pojo.Company.Work, com.example.nettytest._07Protobuf.pojo.Company.Work.Builder, com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder> worksBuilder_;

      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public java.util.List<com.example.nettytest._07Protobuf.pojo.Company.Work> getWorksList() {
        if (worksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(works_);
        } else {
          return worksBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public int getWorksCount() {
        if (worksBuilder_ == null) {
          return works_.size();
        } else {
          return worksBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public com.example.nettytest._07Protobuf.pojo.Company.Work getWorks(int index) {
        if (worksBuilder_ == null) {
          return works_.get(index);
        } else {
          return worksBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder setWorks(
          int index, com.example.nettytest._07Protobuf.pojo.Company.Work value) {
        if (worksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorksIsMutable();
          works_.set(index, value);
          onChanged();
        } else {
          worksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder setWorks(
          int index, com.example.nettytest._07Protobuf.pojo.Company.Work.Builder builderForValue) {
        if (worksBuilder_ == null) {
          ensureWorksIsMutable();
          works_.set(index, builderForValue.build());
          onChanged();
        } else {
          worksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder addWorks(com.example.nettytest._07Protobuf.pojo.Company.Work value) {
        if (worksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorksIsMutable();
          works_.add(value);
          onChanged();
        } else {
          worksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder addWorks(
          int index, com.example.nettytest._07Protobuf.pojo.Company.Work value) {
        if (worksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorksIsMutable();
          works_.add(index, value);
          onChanged();
        } else {
          worksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder addWorks(
          com.example.nettytest._07Protobuf.pojo.Company.Work.Builder builderForValue) {
        if (worksBuilder_ == null) {
          ensureWorksIsMutable();
          works_.add(builderForValue.build());
          onChanged();
        } else {
          worksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder addWorks(
          int index, com.example.nettytest._07Protobuf.pojo.Company.Work.Builder builderForValue) {
        if (worksBuilder_ == null) {
          ensureWorksIsMutable();
          works_.add(index, builderForValue.build());
          onChanged();
        } else {
          worksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder addAllWorks(
          java.lang.Iterable<? extends com.example.nettytest._07Protobuf.pojo.Company.Work> values) {
        if (worksBuilder_ == null) {
          ensureWorksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, works_);
          onChanged();
        } else {
          worksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder clearWorks() {
        if (worksBuilder_ == null) {
          works_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          worksBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public Builder removeWorks(int index) {
        if (worksBuilder_ == null) {
          ensureWorksIsMutable();
          works_.remove(index);
          onChanged();
        } else {
          worksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public com.example.nettytest._07Protobuf.pojo.Company.Work.Builder getWorksBuilder(
          int index) {
        return getWorksFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder getWorksOrBuilder(
          int index) {
        if (worksBuilder_ == null) {
          return works_.get(index);  } else {
          return worksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public java.util.List<? extends com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder> 
           getWorksOrBuilderList() {
        if (worksBuilder_ != null) {
          return worksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(works_);
        }
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public com.example.nettytest._07Protobuf.pojo.Company.Work.Builder addWorksBuilder() {
        return getWorksFieldBuilder().addBuilder(
            com.example.nettytest._07Protobuf.pojo.Company.Work.getDefaultInstance());
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public com.example.nettytest._07Protobuf.pojo.Company.Work.Builder addWorksBuilder(
          int index) {
        return getWorksFieldBuilder().addBuilder(
            index, com.example.nettytest._07Protobuf.pojo.Company.Work.getDefaultInstance());
      }
      /**
       * <pre>
       * 相当于List&lt;Work&gt;
       * </pre>
       *
       * <code>repeated .Work works = 4;</code>
       */
      public java.util.List<com.example.nettytest._07Protobuf.pojo.Company.Work.Builder> 
           getWorksBuilderList() {
        return getWorksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.nettytest._07Protobuf.pojo.Company.Work, com.example.nettytest._07Protobuf.pojo.Company.Work.Builder, com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder> 
          getWorksFieldBuilder() {
        if (worksBuilder_ == null) {
          worksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.nettytest._07Protobuf.pojo.Company.Work, com.example.nettytest._07Protobuf.pojo.Company.Work.Builder, com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder>(
                  works_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          works_ = null;
        }
        return worksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final com.example.nettytest._07Protobuf.pojo.Company.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.nettytest._07Protobuf.pojo.Company.Employee();
    }

    public static com.example.nettytest._07Protobuf.pojo.Company.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.nettytest._07Protobuf.pojo.Company.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WorkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Work)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string handle = 3;</code>
     * @return The handle.
     */
    java.lang.String getHandle();
    /**
     * <code>string handle = 3;</code>
     * @return The bytes for handle.
     */
    com.google.protobuf.ByteString
        getHandleBytes();
  }
  /**
   * Protobuf type {@code Work}
   */
  public static final class Work extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Work)
      WorkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Work.newBuilder() to construct.
    private Work(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Work() {
      name_ = "";
      handle_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Work();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Work(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              handle_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Work_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Work_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.nettytest._07Protobuf.pojo.Company.Work.class, com.example.nettytest._07Protobuf.pojo.Company.Work.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HANDLE_FIELD_NUMBER = 3;
    private volatile java.lang.Object handle_;
    /**
     * <code>string handle = 3;</code>
     * @return The handle.
     */
    @java.lang.Override
    public java.lang.String getHandle() {
      java.lang.Object ref = handle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        handle_ = s;
        return s;
      }
    }
    /**
     * <code>string handle = 3;</code>
     * @return The bytes for handle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHandleBytes() {
      java.lang.Object ref = handle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        handle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(handle_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, handle_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(handle_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, handle_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.nettytest._07Protobuf.pojo.Company.Work)) {
        return super.equals(obj);
      }
      com.example.nettytest._07Protobuf.pojo.Company.Work other = (com.example.nettytest._07Protobuf.pojo.Company.Work) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getHandle()
          .equals(other.getHandle())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HANDLE_FIELD_NUMBER;
      hash = (53 * hash) + getHandle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nettytest._07Protobuf.pojo.Company.Work parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.nettytest._07Protobuf.pojo.Company.Work prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Work}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Work)
        com.example.nettytest._07Protobuf.pojo.Company.WorkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Work_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Work_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.nettytest._07Protobuf.pojo.Company.Work.class, com.example.nettytest._07Protobuf.pojo.Company.Work.Builder.class);
      }

      // Construct using com.example.nettytest._07Protobuf.pojo.Company.Work.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        handle_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.nettytest._07Protobuf.pojo.Company.internal_static_Work_descriptor;
      }

      @java.lang.Override
      public com.example.nettytest._07Protobuf.pojo.Company.Work getDefaultInstanceForType() {
        return com.example.nettytest._07Protobuf.pojo.Company.Work.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.nettytest._07Protobuf.pojo.Company.Work build() {
        com.example.nettytest._07Protobuf.pojo.Company.Work result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.nettytest._07Protobuf.pojo.Company.Work buildPartial() {
        com.example.nettytest._07Protobuf.pojo.Company.Work result = new com.example.nettytest._07Protobuf.pojo.Company.Work(this);
        result.id_ = id_;
        result.name_ = name_;
        result.handle_ = handle_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.nettytest._07Protobuf.pojo.Company.Work) {
          return mergeFrom((com.example.nettytest._07Protobuf.pojo.Company.Work)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.nettytest._07Protobuf.pojo.Company.Work other) {
        if (other == com.example.nettytest._07Protobuf.pojo.Company.Work.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getHandle().isEmpty()) {
          handle_ = other.handle_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.nettytest._07Protobuf.pojo.Company.Work parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.nettytest._07Protobuf.pojo.Company.Work) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object handle_ = "";
      /**
       * <code>string handle = 3;</code>
       * @return The handle.
       */
      public java.lang.String getHandle() {
        java.lang.Object ref = handle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          handle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string handle = 3;</code>
       * @return The bytes for handle.
       */
      public com.google.protobuf.ByteString
          getHandleBytes() {
        java.lang.Object ref = handle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          handle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string handle = 3;</code>
       * @param value The handle to set.
       * @return This builder for chaining.
       */
      public Builder setHandle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        handle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string handle = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHandle() {
        
        handle_ = getDefaultInstance().getHandle();
        onChanged();
        return this;
      }
      /**
       * <code>string handle = 3;</code>
       * @param value The bytes for handle to set.
       * @return This builder for chaining.
       */
      public Builder setHandleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        handle_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Work)
    }

    // @@protoc_insertion_point(class_scope:Work)
    private static final com.example.nettytest._07Protobuf.pojo.Company.Work DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.nettytest._07Protobuf.pojo.Company.Work();
    }

    public static com.example.nettytest._07Protobuf.pojo.Company.Work getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Work>
        PARSER = new com.google.protobuf.AbstractParser<Work>() {
      @java.lang.Override
      public Work parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Work(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Work> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Work> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.nettytest._07Protobuf.pojo.Company.Work getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Work_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Work_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rhttpMsg.proto\"J\n\010Employee\022\014\n\004name\030\001 \001(" +
      "\t\022\013\n\003age\030\002 \001(\005\022\r\n\005phone\030\003 \001(\005\022\024\n\005works\030\004" +
      " \003(\0132\005.Work\"0\n\004Work\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030" +
      "\002 \001(\t\022\016\n\006handle\030\003 \001(\tB1\n&com.example.net" +
      "tytest._07Protobuf.pojoB\007Companyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Name", "Age", "Phone", "Works", });
    internal_static_Work_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Work_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Work_descriptor,
        new java.lang.String[] { "Id", "Name", "Handle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
